using System;
using System.Collections.Generic;

namespace Backend.Domain
{
    /// <summary>
    /// Domain model representing a Sales Order header. 
    /// Used for Franchisee/Own Store orders from central inventory.
    /// Maps to AutoCount Sales Order document.
    /// </summary>
    public class SalesOrder
    {
        /// <summary>
        /// Document number (auto-generated by AutoCount if not specified).
        /// </summary>
        public string DocNo { get; set; }

        /// <summary>
        /// Customer/Debtor code (Franchisee or Own Store code in AutoCount).
        /// </summary>
        public string DebtorCode { get; set; }

        /// <summary>
        /// Document date.
        /// </summary>
        public DateTime DocDate { get; set; }

        /// <summary>
        /// Expected delivery date.
        /// </summary>
        public DateTime? DeliveryDate { get; set; }

        /// <summary>
        /// Document description/remarks.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Sales person/agent code.
        /// </summary>
        public string SalesPerson { get; set; }

        /// <summary>
        /// Currency code (e.g., "PHP", "MYR").
        /// </summary>
        public string CurrencyCode { get; set; }

        /// <summary>
        /// Currency exchange rate.
        /// </summary>
        public decimal CurrencyRate { get; set; } = 1;

        /// <summary>
        /// Whether prices are tax-inclusive.
        /// </summary>
        public bool InclusiveTax { get; set; }

        /// <summary>
        /// Indicates if the order is cancelled.
        /// </summary>
        public bool IsCancelled { get; set; }

        /// <summary>
        /// Total amount of the order.
        /// </summary>
        public decimal TotalAmount { get; set; }

        /// <summary>
        /// Line items/details of the order.
        /// </summary>
        public List<SalesOrderLine> Lines { get; set; }
    }

    /// <summary>
    /// Domain model for an individual sales order line item.
    /// </summary>
    public class SalesOrderLine
    {
        /// <summary>
        /// Line number (sequence).
        /// </summary>
        public int LineNumber { get; set; }

        /// <summary>
        /// Stock item code.
        /// </summary>
        public string ItemCode { get; set; }

        /// <summary>
        /// Item description.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Quantity ordered.
        /// </summary>
        public decimal Quantity { get; set; }

        /// <summary>
        /// Unit of measure.
        /// </summary>
        public string UOM { get; set; }

        /// <summary>
        /// Unit price.
        /// </summary>
        public decimal UnitPrice { get; set; }

        /// <summary>
        /// Discount (can be percentage like "5%" or fixed amount).
        /// </summary>
        public string Discount { get; set; }

        /// <summary>
        /// Line subtotal amount.
        /// </summary>
        public decimal SubTotal { get; set; }

        /// <summary>
        /// Tax/GST code.
        /// </summary>
        public string TaxCode { get; set; }

        /// <summary>
        /// Line remarks.
        /// </summary>
        public string Remarks { get; set; }

        /// <summary>
        /// Location/warehouse code.
        /// </summary>
        public string Location { get; set; }
    }
}

