// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pukezienbcenozlqmunf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1a2V6aWVuYmNlbm96bHFtdW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxOTYyMDQsImV4cCI6MjA3NDc3MjIwNH0.WlMo4tKLwQi_FuAQ15LqmXz6UXHHnnEJqNojxG0PnY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});